---
title: "Registro de pacientes que sufrieron insuficiencia cardíaca"
author: "Corina y Jenny"
format: html
toc: true
lang: es
theme: yeti
---

# Introducción

La finalidad de este trabajo es mostrar el resultado de cada consulta, tanto en hombres y mujeres utilizando esta [fuente de datos](https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-020-1023-5).

# Carga de paquetes

```{r}
#| label: carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(knitr)
library(dplyr)
```

# Carga de datos

```{r}
#| label: carga-datos
#| message: false
#| warning: false

pacientes <- read_csv("heart_failure_clinical_records_dataset.csv")
```

## Consulta 1

```{r}
#| label: consulta-01

# Hombres mayores de 70 años, diabéticos y no anémicos mostrados en orden descendente.

pacientes |>
  filter( sex == "1" & diabetes == "1" & anaemia == "0" & high_blood_pressure == "1" & age >=70) |>
select(age, sex, diabetes, anaemia, high_blood_pressure)|>
  arrange(desc(age)) |>
  kable()
```

## Consulta 02

```{r}
#| label: consulta-02

# Mujeres con fracción de eyección entre 20 (inclusive) y 25 (inclusive), en orden descendente de fracción de eyección.

pacientes |>
  filter( sex == "0")|>
  group_by(sex, ejection_fraction, anaemia, diabetes) |>
  arrange(desc(ejection_fraction)) |>
 summarise(ejection_fraction = min (ejection_fraction, na.rm = FALSE),
    ejection_fraction = max (ejection_fraction, na.rm = FALSE),
    n = n()) |>
  kable()
```

## Consulta 3

```{r}
#| label: consulta-03

# Promedio de creatinina sérica de pacientes sobrevivientes y de pacientes fallecidos.

pacientes |>
 group_by(DEATH_EVENT)|>
  summarise(serum_creatinine = mean(serum_creatinine, na.rm = TRUE),
            n = n()) |>
kable()
```

## Consulta 4

```{r}
#| label: consulta-04

# Valor máximo de creatinina sérica de las mujeres que son anémicas o diabéticas.

pacientes |>
  filter(sex == "0" & anaemia ==  "1" | diabetes == "1") |>
  group_by(anaemia, diabetes) |>
  summarise(serum_creatinine = max(serum_creatinine, na.rm = TRUE),
    n = n()) |>
    kable()
```








